### ISSUE TITLE
Typographic errors

### ISSUE THREAD

**Issue by ashinzekene** [ooade/Advanced-JavaScript#1]
Awesome post. Read everything and learnt much. I was able to spot some little errors

#### There is supposed to be a "?" at
https://github.com/ooade/Advanced-JavaScript/blob/master/README.md#L190
https://github.com/ooade/Advanced-JavaScript/blob/master/README.md#213
https://github.com/ooade/Advanced-JavaScript/blob/master/README.md#224
https://github.com/ooade/Advanced-JavaScript/blob/master/README.md#244
https://github.com/ooade/Advanced-JavaScript/blob/master/README.md#261

**Comment by ooade** [comment]
No. Following markdownlint rules (no trailing punctuation in header). Thanks!

**Comment by ashinzekene** [comment]
Not in the header
on lines `190, 213, 224, 244, 261`

**Comment by ashinzekene** [comment]
Not in the header
on lines `190, 213, 224, 244, 261` your ternary

**Comment by ooade** [comment]
@ashinzekene It's not a typo. Check it well, and if it really is, pls send a PR, i don't see anything :sweat_smile:

**Comment by ooade** [comment]
Oh! Now, I see it.. Would you love to send a PR?

**Comment by ashinzekene** [comment]
Sure :smile
