### ISSUE TITLE
Arguments object is deprecated

### ISSUE THREAD

**Issue by ashinzekene** [ooade/Advanced-JavaScript#2]
You used much of the `arguments` object which is deprecated and not allowed in strict mode. A better approach would be to use the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator).

For example 
```js
function highest(){
  return makeArray(arguments).sort(function(a,b){
    return b - a;
  });
}

function makeArray(array){
  return Array().slice.call( array );
}
```
would be achieved like this 
```js
function highest(...args){
  return args.sort(function(a,b){
    return b - a;
  });
}
```

**Comment by ooade** [comment]
Here's what babel transpiles it to:
![babel](https://user-images.githubusercontent.com/11811904/34359750-09220a28-ea5b-11e7-91a3-98aab99381ed.png)

I don't think the `argument `object itself is deprecated. I know of `arguments.callee`. Besides, Babel transpiles to arguments too so i'd say it isn't that bad to use. 

P.S: I think @jeresig is trying to avoid using es6, so it's best we don't add it. Why? It makes it all easy.
And the `arguments.callee` he used was just for illustration which was backed by the named function.

**Comment by ashinzekene** [comment]
Okay. Es6 out. I think the source is old though. Really nice repo.

I wonder why people still prefer constructors to factory functions though

**Comment by ooade** [comment]
I think it all boils down to the implementation details :sweat_smile: 
Although, it does reduce the number of new keywords. Still, it seem a lil bit Verbose compared to the Constructor Pattern.

**Comment by ashinzekene** [comment]
while trying out one of your quizzes. I did this

```js
function Ninja(){
  this.name = "Ninja";
}

assert(name === "Ninja", "Ooops!, leaked out")
```
And you can guess the outcome 😄 

Kyle Simpson and Eric Elliot prefer factory functions though, but as you said, it all boils down to implementation details.

**Comment by ooade** [comment]
It's not mine... Full credits to John Resig... 
You should get something like `name is not defined`
Except you called Ninja which in turn, attaches name to the global context?

**Comment by ashinzekene** [comment]
This actually
```js
function Ninja(){
  this.name = "Ninja";
}

var ninjaA = Ninja(); // This line does the magic
assert( name === "Ninja", "Is undefined, not an instance of Ninja." );
assert( !ninjaA, "Is undefined, not an instance of Ninja." );
```

**Comment by ooade** [comment]
@ashinzekene Yeah, Obviously. By calling it that way, name get attached to the global context. The `new` keyword changes/prevents that :)

**Comment by ashinzekene** [comment]
Nice 😀

**Comment by ashinzekene** [comment]
I just wrapped my head around the fact that the `this` bonding occurs at the call site which is the global context like you said. Did you read Kyle Simpson's book?

**Comment by ooade** [comment]
I read it. That's great. Kyle is awesome :star2:

**Comment by ashinzekene** [comment]
Really awesome. Cool. No wonder you're a boss 😂
